
server:
  port: 9090
spring:
  mvc:
    view:
      suffix: .html
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /static/
  web:
    resources:
      static-locations: META-INF:/resources, classpath:/resources, classpath:/static, classpath:/static/dist
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://101.101.208.101:5432/1907_db
    platform: postgres
    username: postgres
    password: schana1221

# log
logging:
  file:
    path: /home/schana/logs
  level:
    root: info

    org:
      hibernate:
        sql: debug
        type:
          descriptor: trace


# jpa properties
jpa:
  hibernate:
    ddl-auto: validate # When you launch the application for the first time - switch "none" at "create"
    format_sql: true
  show-sql: true
  database: postgresql
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  open-in-view: false
  generate-ddl: true

